based_on = ["default"]

letters_to_lowercase = "éà"

[multiple]
uppercase_versions = true
list = [
    ["ç", "*c"],
    ["Ç", "*c"],
    ["œ", "oe"],
    ["á", "*a"],
    ["â", "*a"],
    ["è", "*e"],
    ["ê", "*e"],
    ["ì", "*i"],
    ["í", "*i"],
    ["î", "*i"],
    ["ò", "*o"],
    ["ó", "*o"],
    ["ô", "*o"],
    ["ù", "*u"],
    ["ú", "*u"],
    ["û", "*u"],
    ["ä", "*a"],
    ["ë", "*e"],
    ["ï", "*i"],
    ["ö", "*o"],
    ["ü", "*u"]
]
