cargo-features = ["profile-rustflags"]

[profile.release]
opt-level = 3
lto = "fat"
rustflags = ["-C", "target-cpu=native", "-Z", "share-generics=y"]

[package]
name = "layout_analyser"
version = "0.1.0"
authors = ["O_X_E_Y <lucoerlemans37@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.3"
serde = {version = "1.0.136", features = ["derive"]}
serde_json = "1.0.79"
fastrand = "1.6.0"
rayon = "1.5.1"
file-chunker = "0.1.1"
anyhow = "1.0.57"
unicode-normalization = "0.1.19"
indexmap = {version = "1.8.1", features = ["serde"]}
clap = {version = "3.1.18", features = ["cargo", "unstable-multicall"]}
shlex = "1.1.0"
fxhash = "0.2.1"
indicatif = {version = "0.16.2", features = ["rayon"]}
toml = "0.5.9"
