#[profile.release]
#opt-level = 3

[package]
name = "layout_analyser"
version = "0.1.0"
authors = ["O_X_E_Y <lucoerlemans37@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.3"
json = "0.12.4"
serde = {version = "1.0.136", features = ["derive"]}
serde_json = "1.0.79"
fastrand = "1.6.0"
rayon = "1.5.1"
adorn = "0.4.0"
