pins = """
..... .xxx.
xxxx. .xxxx 
...x. .....
"""

[defaults]
language = "english"

[weights]
heatmap = [1.5, 0.9]
sfb = 15.0
dsfb = 2.5
scissors = 6.0
inrolls = 1.5
outrolls = 1.1
onehands = 0.6
alternates = 0.7
alternates_sfs = 0.35
redirects = 1.5
bad_redirects = 6.5

# this doesn't do anything yet
[finger_strength]
penalty = 1.0
pinky = 9.0
ring = 13.0
middle = 19.0
index = 18.0