pins = """
..... ..x..
xxxx. ..xxx
..... .....
"""

[defaults]
language = "english"
trigram_precision = 1000

[weights]
heatmap = 1.5
lateral_penalty = 1.0
fspeed = 14.0
dsfb_ratio = 0.11
scissors = 6.0
inrolls = 1.5
outrolls = 1.25
onehands = 0.9
alternates = 0.9
alternates_sfs = 0.6
redirects = 1.5
bad_redirects = 5.0

[weights.max_finger_use]
penalty = 2.5
pinky = 9.0
ring = 16.5
middle = 20.0
index = 19.0

[weights.finger_speed]
base = 1.0
pinky = 2.5
ring = 1.3
middle = 1.1
index = 1.0