pins = """
..... ...x.
..... .xxxx
..... .....
"""

[defaults]
language = "english"

[weights]
heatmap = [1.4, 0.9]
sfb = 15.0
dsfb = 2.5
inrolls = 0.6
outrolls = 0.45
onehands = 0.6
alternates = 0.7
alternates_sfs = 0.35
redirects = 1.0
bad_redirects = 6.5