pins = """
..... .....
xxxx    . .....
..... .....
"""

[defaults]
language = "english"
trigram_precision = 1000

[weights]
heatmap = 0.85
lateral_penalty = 1.3
sfb = 15.0
dsfb = 2.5
scissors = 5.0
inrolls = 1.6
outrolls = 1.3
onehands = 0.8
alternates = 0.7
alternates_sfs = 0.35
redirects = 1.5
bad_redirects = 6.5

[weights.max_finger_use]
penalty = 2.5
pinky = 9.0
ring = 16.5
middle = 19.5
index = 18.0